# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define "vsrx" do |vsrx|
      vsrx.vm.hostname = "vsrx"
      vsrx.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"

      vsrx.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--hwvirtex", "off"]
        vb.cpus = 1
      end
  end



  config.vm.provision "ansible" do |ansible|
      ansible.groups = {
          "all" => ["vsrx"]
      }
      ansible.playbook = "junos_get_facts/pb.junos_get_facts.yaml"
  end
end
