- name: 'Explicit host argument'
  hosts: junos
  connection: local
  gather_facts: no
  collections:
    - juniper.device

  tasks:
    - name: "Get facts"
      facts:
      register: response

    - name: Facts with login credentials
      facts:
        host: "10.x.x.x"
        user: "user"
        passwd: "user123"
        port: "22"

    - name: Facts in telnet mode
      facts:
        host: "10.x.x.x"
        user: "user"
        passwd: "user123"
        port: "23"
        mode: "telnet"