---
name: Ansible lint

"on":
  workflow_call:
    inputs:
      args:
        description: Arguments to be passed to ansible-lint command.
        required: false
        default: ""
        type: string
      setup_python:
        description: If false, this action will not setup python and will instead rely on the already installed python.
        required: false
        default: true
        type: boolean
      working_directory:
        description: The directory where to run ansible-lint from. Default is `github.workspace`.
        required: false
        default: ""
        type: string
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Process inputs
        id: inputs
        shell: bash
        run: |
          if [[ -n "${{ inputs.working_directory }}" ]]; then
            echo "working_directory=${{ inputs.working_directory }}" >> $GITHUB_OUTPUT
          else
            echo "working_directory=${{ github.workspace }}" >> $GITHUB_OUTPUT
          fi
      - name: Set up Python
        if: inputs.setup_python == 'true'
        uses: actions/setup-python@v5
        with:
          cache: pip
          cache-dependency-path: ${{ steps.inputs.outputs.working_directory }}/.git/ansible-lint-requirements.txt
          python-version: "3.11"
      - name: Install ansible-lint from pip
        shell: bash
        run: |
          pip install ansible-compat==24.10.0 ansible-lint
          ansible-lint --version
      - name: Run ansible-lint
        shell: bash
        working-directory: ${{ steps.inputs.outputs.working_directory }}
        run: cd ansible_collections/juniper/device/; ansible-lint